[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eBuild"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [{ name = "bessx", email = "1159066+bessx@users.noreply.github.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["numpy<2", "rdkit", "colorlog", "networkx", "matplotlib"]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov"]
types = ["pyright"]

[project.urls]
Documentation = "https://github.com/deepdrugai/ebuild#readme"
Issues = "https://github.com/deepdrugai/ebuild/issues"
Source = "https://github.com/deepdrugai/ebuild"

[tool.hatch.version]
path = "src/ebuild/__about__.py"

[tool.hatch.envs.dev]
dependencies = ["pytest", "pytest-cov", "pyright"]
[tool.hatch.envs.dev.scripts]
typ = "pyright"
types = "pyright --stats"
typesskip = "pyright --stats --skipunannotated"

[tool.pyright]
include = ["src/ebuild", "tests"]

[tool.coverage.run]
source_pkgs = ["ebuild", "tests"]
branch = true
parallel = true
omit = ["src/ebuild/__about__.py"]

[tool.coverage.paths]
ebuild = ["src/ebuild", "*/eBuild/src/ebuild"]
tests = ["tests", "*/ebuild/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[project.scripts]
ebuild = "ebuild.eBuild:main"

[tool.ruff]
line-length = 142

[tool.ruff.lint]
ignore = ["N", "SLF", "F541", "BLE001", "EM", "TRY0", "FBT", "PLR2004", "T20"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
